<?php

namespace System\Configs;

// System constants
class Constants {
    const SYSTEM_DIR_NAME = 'system';
    const SYSTEM_CORE_DIR_NAME = 'Core';
    const SYSTEM_CONFIGS_DIR_NAME = 'Configs';
    const SYSTEM_HELPERS_DIR_NAME = 'Helpers';
    const SYSTEM_LIBRARIES_DIR_NAME = 'Libraries';
    const SYSTEM_PATH = BASEPATH . self::SYSTEM_DIR_NAME . DIRECTORY_SEPARATOR;
    const SYSTEM_CONFIGS_DIR_PATH = self::SYSTEM_PATH . self::SYSTEM_CONFIGS_DIR_NAME . DIRECTORY_SEPARATOR;
    const SYSTEM_CORE_DIR_PATH = self::SYSTEM_PATH . self::SYSTEM_CORE_DIR_NAME . DIRECTORY_SEPARATOR;
    const SYSTEM_HELPERS_DIR_PATH = self::SYSTEM_PATH . self::SYSTEM_HELPERS_DIR_NAME . DIRECTORY_SEPARATOR;
    const SYSTEM_LIBRARIES_DIR_PATH = self::SYSTEM_PATH . self::SYSTEM_LIBRARIES_DIR_NAME . DIRECTORY_SEPARATOR;
}
